.TH topic_snapping 1 "" "GRASS 7.0.2" "Grass User's Manual"
.SH Topic: snapping
\fINote: see also the corresponding keyword snapping for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
t.snap
T}	 	T{
Snaps temporally the maps of a space time dataset.
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2015
GRASS Development Team,
GRASS GIS 7.0.2 Reference Manual
