.TH topic_latitude 1 "" "GRASS 7.0.2" "Grass User's Manual"
.SH Topic: latitude
\fINote: see also the corresponding keyword latitude for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
r.latlong
T}	 	T{
Creates a latitude/longitude raster map.
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2015
GRASS Development Team,
GRASS GIS 7.0.2 Reference Manual
