.TH wxGUI.components 1 "" "GRASS 7.0.2" "Grass User's Manual"
.SH wxGUI Components
List of available \fIwxGUI\fR components:
.RS 4n
.IP \(bu 4n
3D Viewer (nviz)
.IP \(bu 4n
Animation tool,
available as a command line tool \fIg.gui.animation\fR
.IP \(bu 4n
Attribute Table Manager,
available also as a command line tool \fIg.gui.dbmgr\fR
.IP \(bu 4n
Cartographic Composer,
available also as a command line tool \fIg.gui.psmap\fR
.IP \(bu 4n
Graphical Modeler,
available also as a command line tool \fIg.gui.gmodeler\fR
.IP \(bu 4n
Ground Control Points Manager,
available also as a command line tool \fIg.gui.gcp\fR
.IP \(bu 4n
Interactive Scatter Plot Tool
.IP \(bu 4n
Map Swipe,
available also as a command line tool \fIg.gui.mapswipe\fR
.IP \(bu 4n
Supervised Classification Tool,
available also as a command line tool \fIg.gui.iclass\fR
.IP \(bu 4n
Configuration tool for r.li modules, \fIg.gui.rlisetup\fR
.IP \(bu 4n
Timeline Tool,
available also as a command line tool \fIg.gui.timeline\fR
.IP \(bu 4n
Vector Digitizer,
available also as a command line tool \fIg.gui.vdigit\fR
.IP \(bu 4n
Vector Network Analysis Tool
.RE
.PP
\fI$Date: 2014\-04\-19 19:50:06 +0200 (Sat, 19 Apr 2014) $\fR
.PP
Main index |
wxGUI index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2015
GRASS Development Team,
GRASS GIS 7.0.2 Reference Manual
