.TH displaydrivers 1 "" "GRASS 7.0.4" "Grass User's Manual"
.SH Display drivers
The current command line rendering mechanism is direct rendering into
a file. The driver is selected by setting
the GRASS_RENDER_IMMEDIATE variable or by
running \fId.mon\fR module.
.PP
\fBList of available display drivers:\fR
.RS 4n
.IP \(bu 4n
Cairo driver
.IP \(bu 4n
PNG driver
.IP \(bu 4n
PS driver (Postscript)
.IP \(bu 4n
HTMLMAP driver
.RE
.SH SEE ALSO
\fI
d.mon,
variables
\fR
.PP
Main index |
display index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2016
GRASS Development Team,
GRASS GIS 7.0.4 Reference Manual
