.TH topic_transformation 1 "" "GRASS 7.0.4" "Grass User's Manual"
.SH Topic: transformation
\fINote: see also the corresponding keyword transformation for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
i.fft
T}	 	T{
Fast Fourier Transform (FFT) for image processing.
T}
.sp 1
T{
i.ifft
T}	 	T{
Inverse Fast Fourier Transform (IFFT) for image processing.
T}
.sp 1
T{
i.pca
T}	 	T{
Principal components analysis (PCA) for image processing.
T}
.sp 1
T{
i.tasscap
T}	 	T{
Performs Tasseled Cap (Kauth Thomas) transformation.
T}
.sp 1
T{
m.transform
T}	 	T{
Computes a coordinate transformation based on the control points.
T}
.sp 1
T{
v.transform
T}	 	T{
Performs an affine transformation (shift, scale and rotate) on vector map.
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2016
GRASS Development Team,
GRASS GIS 7.0.4 Reference Manual
