.TH topic_multispectral 1 "" "GRASS 7.0.4" "Grass User's Manual"
.SH Topic: multispectral
\fINote: see also the corresponding keyword multispectral for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
i.oif
T}	 	T{
Calculates Optimum\-Index\-Factor table for spectral bands
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2016
GRASS Development Team,
GRASS GIS 7.0.4 Reference Manual
