.TH topic_user_interface 1 "" "GRASS 7.0.4" "Grass User's Manual"
.SH Topic: user interface
\fINote: see also the corresponding keyword user interface for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
g.gui.vdigit
T}	 	T{
Interactive editing and digitization of vector maps.
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2016
GRASS Development Team,
GRASS GIS 7.0.4 Reference Manual
