.TH topic_raster 1 "" "GRASS 7.0.4" "Grass User's Manual"
.SH Topic: raster
\fINote: see also the corresponding keyword raster for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
d.colortable
T}	 	T{
Displays the color table associated with a raster map layer.
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2016
GRASS Development Team,
GRASS GIS 7.0.4 Reference Manual
