.TH topic_mask 1 "" "GRASS 7.0.4" "Grass User's Manual"
.SH Topic: mask
\fINote: see also the corresponding keyword mask for additional references.\fR
.PP
.TS
expand;
lw60 lw1 lw60.
T{
r.mask
T}	 	T{
Creates a MASK for limiting raster operation.
T}
.sp 1
T{
r3.mask
T}	 	T{
Establishes the current working 3D raster mask.
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Full index
.PP
© 2003\-2016
GRASS Development Team,
GRASS GIS 7.0.4 Reference Manual
